# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.5"

env:
  - TOXENV=py27-d110
  - TOXENV=py27-d111

  - TOXENV=py35-d110
  - TOXENV=py35-d111
  - TOXENV=py35-d20


before_install:
  - pip install tox codecov


script:
  - tox -e $TOXENV

before_success:
  - coverage erase

after_success:
  - coverage combine
  - codecov
